### ISSUE TITLE
Not working on Unity 5.6

### ISSUE THREAD

**Issue by ramirofages** [unity3d-jp/AlembicImporter#10]
Hi, I wanted to try this out on unity 5.6 but even the example demos doesn't seem to work. When I hit play the editor freezes and cpu consumption goes to 50% or more.

**Comment by i-saint** [comment]
use package ( https://github.com/unity3d-jp/AlembicImporter/releases/download/20170310/AlembicImporter.unitypackage )
do not clone this repository unless you are trying to build plugin from source.

**Comment by ramirofages** [comment]
Thanks, it is working now.
