### ISSUE TITLE
No point renderer? (also exporter error)

### ISSUE THREAD

**Issue by diftow** [unity3d-jp/AlembicImporter#12]
There used to be a way to render points in an ABC cache, now suddenly there isn't.

The cache I'm trying to use in Unity is generated from a Maya particle physics simulation.
It only works in a several month old version of the Alembic Importer, but the older version has bugs that prevent me from adjusting the start time, so I've tried using several new versions, and the points renderer is missing.

I just need to load either sphere meshes or sprites onto the points so they are rendered, but I'm not a coder, so what can I do?

I've tried using the USD for Unity version of the importer, but still didn't see a points renderer in that as well.

Skype: DIFTOW
Email: Chris@diftow.com

**Comment by i-saint** [comment]
sorry for the inconvenience. PointRenderer was removed, but I will add new overhauled one soon. I will hurry up.

PointRenderer was implemented specifically to render balls in [The Gift movie](https://www.youtube.com/watch?v=XyMQ-cgJrJo&feature=youtu.be&t=3m13s). so it was not flexible and hard to use: special shaders/materials are required. but thanks to a new feature introduced in Unity 5.5 ([Graphics.DrawMeshInstanced](https://docs.unity3d.com/550/Documentation/ScriptReference/Graphics.DrawMeshInstanced.html)), PointRenderer can be made more easy to use. it will work with any existing materials. (it will support pre-5.5 but in that case it will be very very slow)

**Comment by diftow** [comment]
Thanks for responding so quickly. Will the updated version allow me to use other references, such as a camera-facing sprite I made or an FBX of a sphere? I believe the previous system only let me use .asset

**Comment by i-saint** [comment]
1. you can use any existing materials. as I wrote above.
2. I think I can ship it in next week.

**Comment by i-saint** [comment]
new package is released. that has new AlembicPointsRenderer.

my comment above was wrong. if instancing is enabled, it only works with materials/shaders which support instancing. and most of existing shaders are not support instancing. (I thought Unity >=5.5 can automatically generate both instancing/non-instancing version of shaders, but not the case)

new package includes shaders that support instancing ("Alembic/Standard Instanced", "Alembic/Transparent Instanced", "Alembic/Billboard Instanced"). "Alembic/Billboard Instanced" is billboard shader (= camera-facing shader). I think it is what you need.
and sort option is added on AlembicPointCloud. if it is enabled, points are sorted by distance from the object in Sort From field. it is intended to sort points by distance from camera to render transparent meshes. I think you also need it.

**Comment by ramirofages** [comment]
Hi, I'm trying to use the AlembicPointsRenderer but can't figure out exactly where to put it. I have an animation imported in alembic that I would like to visualize as points instead of regular geometry. 

I tried to replace the mesh renderer that comes with the model for the AlembicPointsRenderer but don't know where to get the mesh from.

**Comment by i-saint** [comment]
if imported alembic file contains point cache, it will be imported as AlembicPointCloud with AlembicPointsRenderer.
there is no other way to use AlembicPointsRenderer without  point cache. if you want to do it, you need to write script. (I won't add that functionality to AlembicImporter because it is completely unrelated to alembic)

**Comment by ramirofages** [comment]
ohh I see, it's related to alembic then, thanks a lot, I will look into it
