### ISSUE TITLE
Build and run in directX9: application crashed!

### ISSUE THREAD

**Issue by lindyw** [unity3d-jp/AlembicImporter#13]
Whenever my complied scene which included imported alembic model, the application crashed when using DirectX9.  Though,Play Editor in Unity runs fine.
If all alembic is taken away from the scene, the complied application runs perfectly fine.

**Comment by i-saint** [comment]
I can't reproduce the problem. can you send me your Editor.log ( https://docs.unity3d.com/Manual/LogFiles.html ), and reproducible scene or .abc file?

BTW, playing alembic is heavy task. I don' t think D3D11-incapable machine can do it with practical speed. I recommend to drop D3D9 support. (I will look into the problem, though)

**Comment by lindyw** [comment]
I dropped D3D9 support, Forcing GfxDevice as D3D9, it still keep crashing (after the 'made with unity ' animation played).
Or maybe something wrong with my computer setting / hardware conflict with alembic plugin ?
I am using NVidia Quadro M6000 graphics cards, 120Hz monitor and it was OpenGL -> DirectX9.

Here's the output.log:
[output_log.txt](https://github.com/unity3d-jp/AlembicImporter/files/884814/output_log.txt)
before crash!!! message, there's a warning:
WARNING: BC6H/BC7 texture format is not supported, decompressing texture.

Thanks.

**Comment by i-saint** [comment]
thanks for the info.

I think I figured it out. it is path-related problem. I got another bug report for the same problem.
I will release new package next week that include fixes for this problem. please wait for a moment..

**Comment by lindyw** [comment]
Thanks a lot !!!
Will be happy to wait for the new version package!

**Comment by i-saint** [comment]
new package is released. I think this issue is fixed.
be careful: prefab is not compatible with previous version.

**Comment by lindyw** [comment]
Thanks again.
I am using unity 5.5.0f3 but there is another error: Assets/UTJ/AlembicImporter/Scripts/AlembicPointsRenderer.cs(205,51): error CS0103: The name `m_kwAlembicProceduralInstancing' does not exist in the current context

**Comment by i-saint** [comment]
oops, that's an embarrassing mistake.
your fix is correct. I updated package.
