### ISSUE TITLE
Crashes on open the unity scene

### ISSUE THREAD

**Issue by wagnerdesouza** [unity3d-jp/AlembicImporter#14]
Hi guys, Im using this package but sometimes when I open my scene that is using the alembic, my Unity crashes, so I need to recreate the scene using the prefabs but they are broken as well.

This happen always when I change my unity project to another folder or PC.

**Comment by i-saint** [comment]
as noted in the document, you need to copy StreamingAssets/AlembicData because data is directly streamed from .abc files in this directory.
but yeah, crash is bad. I will make emit error message instead of crash.

**Comment by i-saint** [comment]
new package is released.
there was a path-related bug and I think it was the root cause of your issue. new package includes fix for it.
be careful: prefab is not compatible with previous version.
