### ISSUE TITLE
Random start animation using the same Prefab/Alembic

### ISSUE THREAD

**Issue by wagnerdesouza** [unity3d-jp/AlembicImporter#15]
Would be nice if we can randomize the start time in each copy of the prefab, individually.

**Comment by i-saint** [comment]
you can set AlembicStreamPlayer.m_PlaybackSettings.m_startTime manually or by your script.

**Comment by wagnerdesouza** [comment]
Humm, its not working for me with this file.
https://drive.google.com/open?id=0B46rsvtqnOHnaS1Vam9lYjhUcHc
