### ISSUE TITLE
Latest version is incompatible with FrameCapturer

### ISSUE THREAD

**Issue by jean-moreno** [unity3d-jp/AlembicImporter#16]
Hi,

The latest version did fix the relative path issue (thanks for that!), but now the [FrameCapturer](https://github.com/unity3d-jp/FrameCapturer) scripts won't compile anymore.

Example error:
`ExrOffscreenRecorder.cs(67,38): error CS1061: Type 'UTJ.DataPath' does not contain a definition for 'GetPath' and no extension method 'GetPath' of type 'UTJ.DataPath' could be found. Are you missing an assembly reference?`

Looks like it's because the `DataPath.GetPath()` method got renamed to `DataPath.GetFullPath()`?

**Comment by i-saint** [comment]
ah, sorry. I will fix it.
your guess is correct. workaround is just replacing DataPath.GetPath() with DataPath.GetFullPath().

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20170410
