### ISSUE TITLE
Transform issue with points renderer. Appears to be absolute, cant move them.

### ISSUE THREAD

**Issue by diftow** [unity3d-jp/AlembicImporter#17]
Point cache/renderer location doesn't update with transform changes. They need to be relative, not just absolute. If I move the entire ABC prefab, the points still spawn & render at 0,0,0. I need to be able to move the cached particle simulation around, because it is part of a much larger scene in Unity.

Also, is it possible to keyframe the start time?

**Comment by diftow** [comment]
What part of your code handles the position of the alembic points? I can do some basic code, but there's so much here between the C++ & C#, that I'm getting lost xD

**Comment by i-saint** [comment]
I will work on it next week but I think you can fix it easily if you know basics of shader programming. you need to add some code to handle local position in AlembicPointsRenderer.Flush().

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20170426

**Comment by kidapu** [comment]
@i-saint 
I want to translate the Alembic model relatively with parent gameobject in Unity.
Is this possible with the current version of `AlembicForUnity`?
I can't do that.
Do I need some Export or Import setting?

**Comment by kidapu** [comment]
@i-saint Thank you for your advice!

@clusty How about the above my question?

**Comment by clusty** [comment]
To make sure I understand right:
Say your alembic model shows up at (-500,0,0) in the world, you'd like it to appear at (0,0,0) ?
If this is it, just add a parent to your alembic prefab and place this parent at (500,0,0)

**Comment by kidapu** [comment]
@clusty 
Mmm, I can't do that...

My whole procedure is below.

- Create 3D model animation in blender. It only contains cube animation, cube moves from (0,0,0) to (1,0,0).
- Export it with alembic format.
- Import to Unity with `AlembicForUnity`
- Before playing Unity, place alembic parent at (10,0,0), and place alembic prefab at (0,0,0). Then alembic prefab is at (10,0,0). And I hoped to my alembic prefab to move from (10,0,0) to (11,0,0).
- But when I play Unity, alembic prefab goes back to (0,0,0) and start animation to (1,0,0). Inspete of the parent gameobject remains to place at (10,0,0). 

Do you know any solution?

**Comment by cguer** [comment]
Hi @kidapu, we just ran a few tests and are getting the expected behavior with the following steps:

1. Add alembic prefab to scene
2. Create parent object
3. Place alembic prefab as a child of the parent
4. Transform parent to (10,0,0)

When I play in Unity, the alembic prefab then moves from (10,0,0) to (11,0,0) as expected.  Could you try the same steps and let me know if you get the same result or if you alembic still "jumps" back to the center of the scene?

**Comment by kidapu** [comment]
@cguer 
I tried same step, but my alembic still jumps back to the center.
 
I upload a simple unity project, this can reproduce what I say.

https://github.com/kidapu/alembic-pos-issue

This project needs to install AlembicForUnity.unitypackage.

**Comment by cguer** [comment]
Thanks for the test project @kidapu, I tried running your example but it seems to be using code from a very old version of the Alembic package (with the `UTJ.Alembic` namespace).

What version of the Alembic package are you currently using?

**Comment by kidapu** [comment]
@cguer 
I found AlembicForUnity.unitypackage download link, which is written in [Reademe](https://github.com/unity3d-jp/AlembicForUnity#alembic-for-unity).  

> Latest package: [AlembicForUnity.unitypackage](https://github.com/unity3d-jp/AlembicImporter/releases/download/20180413/AlembicForUnity.unitypackage) Do not clone this repository unless you are trying to build plugin from source.

I think it was built on 2018/04/13.

Do I need to clone the latest git repository, and build it to solve my issue?

**Comment by cguer** [comment]
For reference, conversation has been moved to this issue https://github.com/unity3d-jp/AlembicForUnity/issues/293
