### ISSUE TITLE
Billboard Shader questions

### ISSUE THREAD

**Issue by diftow** [unity3d-jp/AlembicImporter#18]
1. How do I make it work with other geometry, like a cylinder instead of a quad?
When I try to use the shader with other geometry I made, it doesn't work.
This is a good fallback if the target platform can't support alpha well.

2. I was able to figure out how to add a normal map to the billboard shader (makes it look like a sphere), but couldn't get alpha working with it. There is alot going on in this shader, so could use some guidance.

**Comment by i-saint** [comment]
1. it's just working as expected on may machine. send me your Editor.log and captured movie or I can't investigate it.
2. read this and set blend mode properly. https://docs.unity3d.com/Manual/SL-Blend.html
