### ISSUE TITLE
motion vector support

### ISSUE THREAD

**Issue by matumu20** [unity3d-jp/AlembicImporter#20]
It seeems that alembic does not supported in motion vector calculation in Unity (I tested on Unity 5.5).
Might 2 possible solutions exist?

#1. Embed motion vector in alembic and Unity's AlembicImporter suport it.
#2. Unity itself calculate motion vector per vertex not only skinnedMesh but also other renderer. (In this case, consideration of topology change might be a problem.)

I think #2 will be preferred because a user can leave all motion vector calcs to Unity.
And it may be important in case fbx and abc co-exists in one unity scene.

However #2 will take long time to be implemented in Unity, 
I hope AlembicImporter support reading motion vector.
If this function is already implemented in AlembicImporter, I'm sorry...

**Comment by i-saint** [comment]
Motion vector calculation and subframe interpolation are on the plan as we got requests from our cinematics team. ETA: 1-2 months.
Our plan is #1 plus compute-motion-vector-on-the-fly option (in AlembicImporter, if topology is constant). that means, you need to use special shader (we will provide) to render motion vectors. It is bit inconvenient, but I think there is no other viable options.

**Comment by matumu20** [comment]
Thank you for your rapid reply.

> compute-motion-vector-on-the-fly
This sounds good.

But, as you mentioned, using special shader may be a problem in some cases.
So, in the future, it would be preferred that Unity's standard shader includes such a feature or #2 is implemented (all types of renderer support vertex based motion vector).

Anyway, I'm loonking forward to the implementation of your plan.


By the way, is subframe interpolation considered in skinnedMeshRenderer(fbx) in Unity's motion vector?
If so, how many samples are calculated?

**Comment by i-saint** [comment]
sorry for delayed response.
recent versions support interpolation and motion vector generation. motion vector will be stored in uv2,3. see AlembicMotionVectors.cginc.
