### ISSUE TITLE
Unity crashing

### ISSUE THREAD

**Issue by Chadt54** [unity3d-jp/AlembicImporter#21]
Hello, Unity keeps crashing on export when exporting large scenes but I think I have found the problem. It appears that when marshalling the data from C# to C++ the C# data isn't being pinned down, so when the GC starts collecting it moves the data to another location in memory while the C++ function is trying to use it resulting in bad pointers, so I went ahead and pinned it down before the C++ function is called, and now it no longer crashes on export. Since I'm not familiar with using Git, can you please check, and if this is correct, modify the source to this code?

----- In file AlembicExporter.cs ----
public static void CaptureMesh(AbcAPI.aeObject abc, Mesh mesh, Cloth cloth, MeshBuffer dst_buf)
        {
            dst_buf.indices = mesh.triangles;
            dst_buf.uvs = mesh.uv;
            if (cloth == null)
            {
                dst_buf.vertices = mesh.vertices;
                dst_buf.normals = mesh.normals;
            }
            else
            {
                dst_buf.vertices = cloth.vertices;
                dst_buf.normals = cloth.normals;
            }
            var data = new AbcAPI.aePolyMeshData();
            if (dst_bufIndicesHandle != null && dst_bufIndicesHandle.IsAllocated)
                dst_bufIndicesHandle.Free();
            dst_bufIndicesHandle = GCHandle.Alloc(dst_buf.indices, GCHandleType.Pinned);
            data.indices = GetArrayPtr(dst_buf.indices);
            if (dst_bufVerticesHandle != null && dst_bufVerticesHandle.IsAllocated)
                dst_bufVerticesHandle.Free();
            dst_bufVerticesHandle = GCHandle.Alloc(dst_buf.vertices, GCHandleType.Pinned);
            data.positions = GetArrayPtr(dst_buf.vertices);
            if(dst_buf.normals != null)
            {
                if (dst_bufNormalsHandle != null && dst_bufNormalsHandle.IsAllocated)
                    dst_bufNormalsHandle.Free();
                dst_bufNormalsHandle = GCHandle.Alloc(dst_buf.normals, GCHandleType.Pinned);
                data.normals = GetArrayPtr(dst_buf.normals);
            }
            if(dst_buf.uvs != null)
            {
                if (dst_bufUvsHandle != null && dst_bufUvsHandle.IsAllocated)
                    dst_bufUvsHandle.Free();
                dst_bufUvsHandle = GCHandle.Alloc(dst_buf.uvs, GCHandleType.Pinned);
                data.uvs = GetArrayPtr(dst_buf.uvs);
            }
            data.positionCount = dst_buf.vertices.Length;
            data.indexCount = dst_buf.indices.Length;

            AbcAPI.aePolyMeshWriteSample(abc, ref data);
        }
        static GCHandle dst_bufIndicesHandle;
        static GCHandle dst_bufVerticesHandle;
        static GCHandle dst_bufNormalsHandle;
        static GCHandle dst_bufUvsHandle;

**Comment by i-saint** [comment]
Thank you very much for the informative feedback! I will check and merge your fix.

**Comment by i-saint** [comment]
latest package includes fix for this problem.
