### ISSUE TITLE
UVs and Normals not exporting

### ISSUE THREAD

**Issue by Chadt54** [unity3d-jp/AlembicImporter#22]
Since this problem is slightly different from the previous post, I decided to post a new issue. Once I got the exporter to run without crashing, it seems that when I import the alembic data into 3ds Max or Maya, the normals and the UV data are lost, or are possibly in the alembic file but aren't being read by Max or Maya (corrupted?).

Is there something I'm doing wrong? Or, can you help me investigate the problem?

**Comment by Chadt54** [comment]
No help at all?

**Comment by i-saint** [comment]
I will investigate, but I have no time right now.

**Comment by Chadt54** [comment]
Ok, thank you

**Comment by Chadt54** [comment]
Scratch that, I think it's just a 3ds Max problem. I had tried importing to Maya but that was a long time ago and with different data that could have been erroneous to begin with at the time I tried importing. But, trying again with both applications, Maya is now showing UVs (our main app is 3ds). So no need to resolve this issue on the plugin's front.

Thanks for your help

**Comment by 3dsMaxtotheMax** [comment]
I only dealt with exporting from Unity, not importing. Sorry, I'm not sure how to help you.

Try importing the abc file into Blender to check that the data is actually in the file and not an issue with Unity.

**Comment by Chadt54** [comment]
I only dealt with exporting from Unity, not importing. Sorry, I'm not sure how to help you.

Try importing the abc file into Blender to check that the data is actually in the file and not an issue with Unity.
