### ISSUE TITLE
Cloth Export

### ISSUE THREAD

**Issue by Chadt54** [unity3d-jp/AlembicImporter#24]
I have a character with animation (using mecanim) using skin, I've added the cloth component to the clothes, when I try to export the scene using alembic there are no problems, but when I try to import this scene into 3ds Max(Exocortex)/Maya/Blender, all three programs instantly crash. But, if I import using 3ds Max's default alembic importer, it doesn't crash, but the mesh with the cloth component added is very odd. The transform looks wrong, along with all the triangles in the mesh being out of order creating a very corrupted-looking mesh.

Is cloth exporting actually supported by the plugin? If not, then that explains the problem, but if so can someone look into this problem?

**Comment by i-saint** [comment]
cloth export is supported and it is working at least in simple case. can you send me reproducible project?
I think pinning problem you mentioned in case https://github.com/unity3d-jp/AlembicImporter/issues/21 is possible cause.

**Comment by Chadt54** [comment]
Here's a project I created that contains the minimal necessary to reproduce. The scene will export ok, but crashes on 3ds Max(Exocortex) and Maya import.

[ClothCrashExample.zip](https://github.com/unity3d-jp/AlembicImporter/files/1130523/ClothCrashExample.zip)

**Comment by i-saint** [comment]
thanks, I will look into it.

**Comment by i-saint** [comment]
sorry for delayed response. latest package includes fix for this problem.
![crashcharacter](https://user-images.githubusercontent.com/1488611/35209217-e47ea222-ff8f-11e7-9431-51ad559d33fc.gif)
