### ISSUE TITLE
Unity 2017.1.0f3 Crash on Import

### ISSUE THREAD

**Issue by VRPlayhouse** [unity3d-jp/AlembicImporter#25]
Error Context:

Registering platform support modules:
Platform assembly: G:\Unity\Editor\Data\Mono\lib\mono\2.0\Boo.Lang.Compiler.dll (this message is harmless)
Platform assembly: G:\Unity\Editor\Data\Mono\lib\mono\2.0\Boo.Lang.dll (this message is harmless)
Platform assembly: G:\Unity\Editor\Data\Mono\lib\mono\2.0\Boo.Lang.Parser.dll (this message is harmless)
Platform assembly: G:\Unity\Editor\Data\Mono\lib\mono\2.0\UnityScript.Lang.dll (this message is harmless)
Registered platform support modules in: 0.0395125s.
Native extension for WindowsStandalone target not found
Native extension for Android target not found
Load scene 'Temp/__Backupscenes/0.backup' time: 0.152575 ms 
Crash!!!
...
...
...
========== OUTPUTING STACK TRACE ==================

0x00007FFFBAC337B6 (abci) aeCreateContext
0x0000000034637F6A (Mono JIT Code) (wrapper managed-to-native) UTJ.Alembic.AbcAPI:aiPolyMeshFillVertexBuffer (UTJ.Alembic.AbcAPI/aiSample,int,UTJ.Alembic.AbcAPI/aiPolyMeshData&)
0x0000000034634EFC (Mono JIT Code) [G:\Daydream\Assets\UTJ\Alembic\Scripts\Importer\AlembicMesh.cs:241] UTJ.Alembic.AlembicMesh:AbcSampleUpdated (UTJ.Alembic.AbcAPI/aiSample,bool) 
0x0000000034633D39 (Mono JIT Code) [G:\Daydream\Assets\UTJ\Alembic\Scripts\Importer\AlembicElement.cs:28] UTJ.Alembic.AlembicElement:SampleCallback (intptr,UTJ.Alembic.AbcAPI/aiSample,UTJ.Alembic.Bool) 
0x0000000034569E5F (Mono JIT Code) (wrapper native-to-managed) UTJ.Alembic.AlembicElement:SampleCallback (intptr,UTJ.Alembic.AbcAPI/aiSample,UTJ.Alembic.Bool)
0x00007FFFBAC2F070 (abci) aeCreateContext
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFBA98F1BE)
0x00007FFFBA98F1BE (abci) 
0x00007FFFBAC2CEA8 (abci) aeCreateContext
0x0000000034633AEE (Mono JIT Code) (wrapper managed-to-native) UTJ.Alembic.AbcAPI:aiUpdateSamplesEnd (UTJ.Alembic.AbcAPI/aiContext)
0x000000003463395A (Mono JIT Code) [G:\Daydream\Assets\UTJ\Alembic\Scripts\Importer\AlembicStream.cs:384] UTJ.Alembic.AlembicStream:ProcessLateUpdateEvent () 
0x0000000034633803 (Mono JIT Code) [G:\Daydream\Assets\UTJ\Alembic\Scripts\Importer\AlembicStreamPlayer.cs:61] UTJ.Alembic.AlembicStreamPlayer:LateUpdate () 
0x00000000008D69F2 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FFFE7115B63 (mono) [c:\buildslave\mono\build\mono\mini\mini.c:4937] mono_jit_runtime_invoke 
0x00007FFFE706872D (mono) [c:\buildslave\mono\build\mono\metadata\object.c:2623] mono_runtime_invoke 
0x000000014140A365 (Unity) scripting_method_invoke
0x0000000141402311 (Unity) ScriptingInvocation::Invoke
0x0000000141159B8B (Unity) MonoBehaviour::CallMethodIfAvailable
0x000000014117231F (Unity) MonoBehaviour::CallUpdateMethod
0x0000000140DD3336 (Unity) BaseBehaviourManager::CommonUpdate<LateBehaviourManager>
0x0000000140DD340F (Unity) LateBehaviourManager::Update
0x00000001410B5563 (Unity) `InitPlayerLoopCallbacks'::`41'::PreLateUpdateScriptRunBehaviourLateUpdateRegistrator::Forward
0x00000001410B334B (Unity) PlayerLoop
0x000000014010835E (Unity) Application::UpdateScene
0x000000014012C1D7 (Unity) Application::EnterPlayMode
0x000000014012D307 (Unity) Application::SetIsPlaying
0x0000000140130B72 (Unity) Application::TickTimer
0x0000000141A87E5D (Unity) MainMessageLoop
0x0000000141A89827 (Unity) WinMain
0x0000000141CEC8BC (Unity) __tmainCRTStartup
0x00007FF830CF2774 (KERNEL32) BaseThreadInitThunk
0x00007FF831D20D51 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

This is happening any time I try to place an imported prefab into my scene. I cant seem to figure out what is causing it, I'm able to get point clouds to import, but when importing a mesh the scene can't take it. The file sizes range from 4mb to 15mb.

**Comment by i-saint** [comment]
can you send me your .abc file that can reproduce the issue?

**Comment by VRPlayhouse** [comment]
We have done some internal testing and it seems to be the early test files we were using. Our digital artist output new material that seems to work just fine. Thank you for your time.
