### ISSUE TITLE
Android Plugin?

### ISSUE THREAD

**Issue by resetme** [unity3d-jp/AlembicImporter#26]
Any possibility that this awesome plugin works on android devices?

Right now the windows version works perfectly with houdini.

Regards.
Fran

**Comment by i-saint** [comment]
there is no plan for now.
I think build this plugin for Android is not so difficult. iOS maybe bit more difficult but should be possible. you can try if you really need it.
but I don't recommend using alembic on Android & iOS as streaming alembic is very IO-intensive and mobile devices have limited bandwidth in general.
