### ISSUE TITLE
Some meshes not importing

### ISSUE THREAD

**Issue by jwvanderbeck** [unity3d-jp/AlembicImporter#27]
Hi,

I am having a problem where some meshes just don't import.  They end up with a MeshFilter with no mesh applied.  I've been trying to track this down and it seems to be meshes that are more complex or dirty.  For example the wall of a building that has many booleans cut out of it for windows and doors.

I'm guessing perhaps it is an issue with how this plugin does the triangulation of the geometry that isn't already tris?

**Comment by i-saint** [comment]
can you send me .abc file that can reproduce the issue?

**Comment by jwvanderbeck** [comment]
I can't.  These are production assets under NDA.  I will see if I can reproduce it at home though with some dummy meshes.

**Comment by i-saint** [comment]
I will reopen if I get data or detailed information.

**Comment by jwvanderbeck** [comment]
Sorry for that.  I wasn't feeling well this weekend.

I put together a simple model with some booleans.  It doesn't exhibit the issue of a missing mesh, but it does show a bad triangulation issue and most likely they are connected.  I am going to attach a zip files that contains two alembic files.  test_building and test_ building_t.  The only difference between them is that in _t I triangulated the booleaned mesh BEFORE exporting it rather than let the importer do it.

test_building when imported has the booleaned mesh all messed up, with the holes essentially filled in by overlapping triangles.  It also oddly has other parts looking inverted and I'm not sure what is up with that.

test_building_t imports as expected.

Alembic import settings are set to no streaming, normals from file, and tangents to split.
[alembic_test.zip](https://github.com/unity3d-jp/AlembicImporter/files/1282991/alembic_test.zip)

**Comment by jwvanderbeck** [comment]
@i-saint Just curious if you were able to reproduce the issue on your end or if you need anything else from me?

**Comment by i-saint** [comment]
non-convex polygons cause unexpected result. just convert them to convex.
