### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by OnurKalkan** [unity3d-jp/AlembicImporter#28]
Hello,
First of all thanks for the asset. It works nice. Good work.
I want to use the asset on iPad too. I am new on writing plugins for Unity. I would like to learn if there is possibility to make the asset work on iOS too. Currently I am working on and I wonder your opinion. 
Can you guide me on this? Maybe we can bring iOS support too?
Thanks in advance.
Onur.

**Comment by i-saint** [comment]
there is no plan for this plugin itself. but native vertex cache support (for Unity engine itself. not as plugin) is planned. if it is done, vertex cache will be available all platforms. (not sure when it will be done, though..)
