### ISSUE TITLE
Framerate issues using Alembic Importer with just one model

### ISSUE THREAD

**Issue by pdoudkine** [unity3d-jp/AlembicImporter#30]
Hi there!

I just tried to use Alembic Importer to import a model from Maya.  
Noticed that framerate tanked to <30 fps while model was animating and to <10 fps if the model is duplicated.  

Troubleshooting revealed that the bottleneck occurs at:
AlembicStream.AbcUpdateElements()\
AbcAPI.aiXformGetData()

Any advice to resolve this issue?

**Comment by i-saint** [comment]
nothing I can say with this little info.
