### ISSUE TITLE
Was `Submesh per UV tile` removed at Pre-release of 1.0f1?

### ISSUE THREAD

**Issue by sest9214** [unity3d-jp/AlembicImporter#35]
Hi,  

I used "Submesh per UV tile" in latest release version.
However, with Pre-release 1.0f1, I cannot assign more than one material even if I import the .abc file that I split the UV tile. 

If there is a way to solve it easily by myself, could you tell me?

**Comment by i-saint** [comment]
it was removed. you need to split objects before exporting .abc

**Comment by i-saint** [comment]
I'm working on adding face set support. it will be better substitute for "Submesh per UV tile".
