### ISSUE TITLE
Point Cloud Rotation and Scale? 

### ISSUE THREAD

**Issue by ShawnFrueh** [unity3d-jp/AlembicImporter#36]
Is it possible to get point rotation\scale support Through the alembic Point cloud? Currently there is Point Size but this is a global setting.

**Comment by i-saint** [comment]
Alembic's Points schema doesn't support it, so we won't do it.
it is certainly possible but not easy. make data and store it in custom property (this will be done in DCC tools), and write scripts and shaders to handle it.
