### ISSUE TITLE
Camera FOV behaviour is weird / somehow dependant on Game View resolution

### ISSUE THREAD

**Issue by soraryu** [unity3d-jp/AlembicImporter#37]
For some alembic files that I have, the embedded camera fov seems to be dependent on camera resolution. I got the values to be correct by changing the GameView size to exactly the pixel size the files where created in, but still from time to time the fov value just jumped to something else entirely.

Even if the "fov dependant on camera pixel size" is by design (which it might well be), at least Unity should behave predictable when reading out these values.

I attached a file with that weird behaviour (the cam is called "sc230_camShape").

[alembic_file_custom_fov.zip](https://github.com/unity3d-jp/AlembicImporter/files/1571936/alembic_file_custom_fov.zip)

**Comment by i-saint** [comment]
you can select camera FOV behavior with "Aspect Ratio Mode" in import settings.
![aspect_ratio_mode](https://user-images.githubusercontent.com/1488611/35210522-eb96a1e4-ff95-11e7-86f6-9b6d568018aa.png)
