### ISSUE TITLE
Multi Uv sets to Unity3d

### ISSUE THREAD

**Issue by frideal** [unity3d-jp/AlembicImporter#38]
When using AlembicForUnity import.abc file to Unity3d? I meet one problem, In Maya i have double uv sets for my object. but when import .abc file to Unity3d , my object just have only one UV sets? Does alembic support multi uv sets?

**Comment by i-saint** [comment]
Alembic's PolyMesh schema doesn't support multiple uv sets. so we won't support it.
it is certainly possible (by using custom properties), but it is not easy.

**Comment by i-saint** [comment]
I just realized Maya can export additional uv sets as extension attribute. I will add support importing it.

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180201

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180205
