### ISSUE TITLE
Material Face Assignments Ignored

### ISSUE THREAD

**Issue by EddieSoloProjects** [unity3d-jp/AlembicImporter#39]
I used a test character and exported from Maya 2017 with the Material Face Assignments turned on. In Unity it creates only one material assignment. I double checked the Alembic in Isotropix Clarisse and it has individual assignments for the shirt, pants skin etc...

**Comment by ShawnFrueh** [comment]
Is it possible to have multiple materials without splitting the mesh into submeshes similar to how an FBX import works? Splitting up the mesh will introduce more draw calls.

**Comment by i-saint** [comment]
@ShawnFrueh it's simply impossible. FBX importer also splits into submeshes.
if you want to draw multiple materials with single draw call, you can emulate it with special shaders (e.g. write a shader that has array of albedo colors and index it with material IDs)

**Comment by EddieSoloProjects** [comment]
I think you misunderstand. I don't need a single draw call. I need it to actually create the proper number of materials for each Face/Material assignment. And as I said in the first post. It works this way in othe software that uses Alembic.

**Comment by i-saint** [comment]
@EddieSoloProjects yeah, I understand what you said. face set support is already implemented and it is in testing phase. I wish you to test if you can..  https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180201

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180201

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180205
