### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by ShawnFrueh** [unity3d-jp/AlembicImporter#40]
When enabling Turn Quad Edges, I get the error "FileNotFoundException" even though the file exists. If I try to re-Import the file I still get the issue. (Latest release 1.0f1)

Is there a way to get the file to load in after that issue occurs?

**Comment by ShawnFrueh** [comment]
It seems it's only if you are adding/changing the file within a folder structure. Bringing it back out to the Assets base it reloads just fine.

**Comment by ShawnFrueh** [comment]
So I ran into this again today with the latest build. It is now constantly happening. If you have a folder that has _Assets at the end, I get the error. Making a folder named "_Example_Assets" When reimporting the alembic in that folder I get the error.

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180201

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180205
