### ISSUE TITLE
TOTALLY BROKEN

### ISSUE THREAD

**Issue by EddieSoloProjects** [unity3d-jp/AlembicImporter#41]
Does not work on Drag and drop of alembic file. Does not see .abc files on asset import new.

I am downloading the link from the main GitHub page which says it is the newest

https://github.com/unity3d-jp/AlembicImporter

It's Wrong. It doesn't work at all.

The one on the top of this page does seem to work. But you right click on the timeline and "Load Clip" to play animation
Alembic Importer 1.0f1
https://github.com/unity3d-jp/AlembicImporter/releases

At NO TIME can you load an Alembic file with "Import New Asset" because it can't even find the file extension.

**Comment by i-saint** [comment]
try latest package.
