### ISSUE TITLE
Loop Time randomly gets set to disabled.

### ISSUE THREAD

**Issue by ShawnFrueh** [unity3d-jp/AlembicImporter#42]
Version: (Alembic Importer 1.0f1)
Unity: 20173.0p1

Every time a project is opened or reloaded the "Loop Time" on the clip gets set to disabled(0) even though it had been set to enabled(1).

**Comment by i-saint** [comment]
I can't control this behavior. (changes for imported assets will be reverted when a project is opened or reloaded)
I will add workaround for it if I got idea..

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180205
