### ISSUE TITLE
Alembics are imported at wrong frame rate

### ISSUE THREAD

**Issue by Chosko** [unity3d-jp/AlembicImporter#44]
Frame rates are interpreted wrongly by Alembic Importer. When I export from Maya an abc at X fps, Alembic importer reads it at (X - 1) fps. For instance:

* abc exported from maya at 25 fps. AlembicImporter reads it at 24 fps.
* abc exported from maya at 30 fps. AlembicImporter reads it at 29 fps.
* abc exported from maya at 60 fps. AlembicImporter reads it at 59 fps.

It's not only a visualization error: exporting the very same mesh with the very same animation in FBX there's a timing difference with the alembic during the playback. 
The result is a timeline in which FBXs are evaluated at 25fps while Alembics are evaluated at 24fps. For this reason the same animation in Alembic is longer than in FBX.

![cattura](https://user-images.githubusercontent.com/3297850/35088955-b8f511c0-fc35-11e7-89a0-5b7485a480ea.PNG)

**Comment by i-saint** [comment]
can you send me an example project? (fbx + alembic + timeline, very simple one is enough)

**Comment by Chosko** [comment]
[AlembicExampleProject.zip](https://github.com/unity3d-jp/AlembicImporter/files/1677485/AlembicExampleProject.zip)

**Comment by i-saint** [comment]
thanks. I'll work on it immediately

**Comment by i-saint** [comment]
ok, it was a stupid bug. I will include a fix in the next release.
you can also fix it by replacing AlembicStreamDescriptor.cs with attached file.
[AlembicStreamDescriptor.zip](https://github.com/unity3d-jp/AlembicImporter/files/1678966/AlembicStreamDescriptor.zip)

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180201

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180205
