### ISSUE TITLE
Problem with update of triangles animation

### ISSUE THREAD

**Issue by soygcm** [unity3d-jp/AlembicImporter#46]
Failed setting triangles. Some indices are referencing out of bounds vertices. IndexCount: 1476, VertexCount: 1042
UnityEngine.Mesh:SetIndices(Int32[], MeshTopology, Int32)
UTJ.Alembic.AlembicMesh:AbcUpdate() (at Assets/UTJ/Alembic/Scripts/Importer/AlembicMesh.cs:402)
UTJ.Alembic.AlembicStream:AbcUpdateElements(AlembicTreeNode) (at Assets/UTJ/Alembic/Scripts/Importer/AlembicStream.cs:97)
UTJ.Alembic.AlembicStream:AbcUpdateElements(AlembicTreeNode) (at Assets/UTJ/Alembic/Scripts/Importer/AlembicStream.cs:104)
UTJ.Alembic.AlembicStream:AbcUpdateElements(AlembicTreeNode) (at Assets/UTJ/Alembic/Scripts/Importer/AlembicStream.cs:104)
UTJ.Alembic.AlembicStream:AbcUpdate(Single, Single, Boolean) (at Assets/UTJ/Alembic/Scripts/Importer/AlembicStream.cs:144)
UTJ.Alembic.AlembicStreamPlayer:LateUpdate() (at Assets/UTJ/Alembic/Scripts/Importer/AlembicStreamPlayer.cs:44)

**Comment by i-saint** [comment]
can you send me your .abc file?

**Comment by soygcm** [comment]
I just sent it to you or by mail

**Comment by i-saint** [comment]
confirmed. I will look into it.

**Comment by soygcm** [comment]
Hi.. I make this change and it worked

**AlembicMesh.cs:~371**
```
split.mesh.SetVertices( new List<Vector3>( split.positionCache.Array )  );
split.mesh.SetNormals(new List<Vector3>( split.normalCache.Array ) );
split.mesh.SetTangents(new List<Vector4>( split.tangentCache.Array ) );
split.mesh.SetUVs(0, new List<Vector2>( split.uvCache.Array ) );
split.mesh.SetUVs(2, new List<Vector2>( split.velocitiesXYCache.Array ) );
split.mesh.SetUVs(3, new List<Vector2>( split.velocitiesZCache.Array ) );
```

But the problem now is: there are polygons separated from the main mesh.

**Comment by i-saint** [comment]
I have not examined it deeply yet, but your .abc file seems corrupted. even DCC tools can't render it correctly (tested on Maya and Blender. both shows 'glitchy' effect on some frames).
what tool did you used to make this?

**Comment by soygcm** [comment]
It was made with Cinema

**Comment by i-saint** [comment]
you men Cinema 4D? C4D can render it correctly? (we don't have license and can't test..)

**Comment by soygcm** [comment]
Yes Cinema4D,  we tested on Houdini too and work perfectly

**Comment by i-saint** [comment]
hmm, interesting. adding boundary check for indices may solve the problem.
I will investigate, but it may be a while.

**Comment by soygcm** [comment]
This is other file (made with Houdini), and the result with the changes I post before.
**Houdini**
![Houdini](https://user-images.githubusercontent.com/1345759/35407426-889a26a4-01d1-11e8-8132-995004f0aa36.gif)
**Unity**
![Unity](https://user-images.githubusercontent.com/1345759/35407438-90a37ee0-01d1-11e8-860d-4cdce10258fc.gif)
I will send you the file by mail.

**Comment by i-saint** [comment]
thanks. I figured it out. it's a stupid bug sneaked in latest package..
you can fix it by replacing AlembicMesh.cs with attached file. I will include this fix in next release.

[AlembicMesh.zip](https://github.com/unity3d-jp/AlembicImporter/files/1665441/AlembicMesh.zip)

**Comment by soygcm** [comment]
thank a lot

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180201

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180205
