### ISSUE TITLE
AlembicforUnity 20180122 BUG!

### ISSUE THREAD

**Issue by davoodkharmanzar** [unity3d-jp/AlembicImporter#49]
there is an animated alembic. but i can import just geometries and not animation clip :[
**Unity 2018.1.0b4 + AlembicforUnity 20180122**

https://www.dropbox.com/s/9et61l7rlim633y/cloth.zip?dl=0

**Comment by i-saint** [comment]
thanks for valuable data.
I already fixed this issue in dev branch. I think I can release updated plugin in this week.

**Comment by davoodkharmanzar** [comment]
thanks alot :]
