### ISSUE TITLE
AlembicforUnity 20180201 bug ...

### ISSUE THREAD

**Issue by davoodkharmanzar** [unity3d-jp/AlembicImporter#50]
i got this error after installing on unity 2018.1.0b4 ...

**Extensions/UTJ/Alembic/Scripts/Importer/AlembicMaterial.cs(150,44): error CS0426: The nested type `aiFacesets' does not exist in the type `UTJ.Alembic.AbcAPI'**

**Comment by i-saint** [comment]
AlembicMaterial.cs is no longer in the package. simply delete it.

**Comment by davoodkharmanzar** [comment]
oops! ok :]

**Comment by davoodkharmanzar** [comment]
so ... i can't play any animation on timeline!!

sample: https://www.dropbox.com/s/9et61l7rlim633y/cloth.zip?dl=0

**Comment by i-saint** [comment]
I will fix it, but Alembic Track is more recommended. it should work. (Timeline -> Add -> UTJ.Alembic -> Alembic Track)

**Comment by davoodkharmanzar** [comment]
![capture](https://user-images.githubusercontent.com/10723167/35658181-3f520392-0715-11e8-931c-cb948fa6b7c8.JPG)

**Comment by i-saint** [comment]
can you send me project file? I can't reproduce Alembic Track doesn't work.

**Comment by davoodkharmanzar** [comment]
here is alembic:
https://www.dropbox.com/s/9et61l7rlim633y/cloth.zip?dl=0

the project is nothing special ...
just drag and drop alembic to unity ...
then select it from hierarchy and then in timeline create and then "add from animation clip"

**Comment by i-saint** [comment]
that mean you are not using Alembic Track. please follow the step of  https://github.com/unity3d-jp/AlembicImporter/issues/50#issuecomment-362138295

**Comment by davoodkharmanzar** [comment]
nope ... because i can't find any tracks on that method!! [i mean alembic track]
but i'm using usual method with previous versions of alembic plugin and everything was good!! [except bug situations!!]

**Comment by davoodkharmanzar** [comment]
Crash on playing multi alembics ... dump is attached ...

![capture](https://user-images.githubusercontent.com/10723167/35672574-3c8ab5f2-0754-11e8-8cac-2abd59db67db.JPG)

[Crash_2018-02-01_212830366.zip](https://github.com/unity3d-jp/AlembicImporter/files/1685007/Crash_2018-02-01_212830366.zip)
