### ISSUE TITLE
Alembic 20180201 Crash bug!!

### ISSUE THREAD

**Issue by davoodkharmanzar** [unity3d-jp/AlembicImporter#51]
Crash on playing multi alembics ... dump is attached ...

![capture](https://user-images.githubusercontent.com/10723167/35672702-965cac66-0754-11e8-9bde-1d43dbcbb7ba.JPG)

[Crash_2018-02-01_212830366.zip](https://github.com/unity3d-jp/AlembicImporter/files/1685022/Crash_2018-02-01_212830366.zip)

**Comment by i-saint** [comment]
ah, thanks for the info. this must be fixed.
btw, Animation should work on latest package (I replaced it with new one)
https://github.com/unity3d-jp/AlembicImporter/releases/download/20180201/AlembicForUnity.unitypackage

**Comment by davoodkharmanzar** [comment]
well ... i'm trying with this new package ... but same crash ... hope to see un buggy version as good as previous versions that i can working with alembics like as normal objects :]

**Comment by i-saint** [comment]
obviously you are not reading what I wrote.
and this package is still "pre-release". not official release yet. still testing phase.

**Comment by davoodkharmanzar** [comment]
yup ... i said, hope to see ... not should to see :]

**Comment by i-saint** [comment]
package updated. it includes fix for this issue. I'm keep testing..
https://github.com/unity3d-jp/AlembicImporter/releases/download/20180201/AlembicForUnity.unitypackage

![multi_alembic](https://user-images.githubusercontent.com/1488611/35677769-44fa14cc-0794-11e8-8f3b-0fbc8b45e4b6.png)

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180205

**Comment by davoodkharmanzar** [comment]
its amazing work 👍
thanks :]
