### ISSUE TITLE
AlembicforUnity 20180205 Bug

### ISSUE THREAD

**Issue by davoodkharmanzar** [unity3d-jp/AlembicImporter#54]
import alembic to unity ...
create empty object as timeline ...
drag alembic to it and create animation clip ... everything is working good ...

but when drag and drop new material to alembic ...  timeline animation track does not working and we have to save the scene and open unity again!! and now its working  :\

**Comment by davoodkharmanzar** [comment]
ok ... i refresh plugin ... on new scene ... solved

**Comment by i-saint** [comment]
certainly something wrong is happening when assigning material.. I will investigate.

**Comment by i-saint** [comment]
fixed and package updated.
this problem seems nondeterministic and refreshing plugin doesn't solve it completely.
