### ISSUE TITLE
Vertex normals are not interpolated

### ISSUE THREAD

**Issue by dmm-pete** [unity3d-jp/AlembicImporter#56]
We have alembic files that are stepped every 5 frames in order to reduce the size of the abc file. With interpolation turned on, the animation looks fine, however the lighting does not look good because the shadows/etc. are only updating every 5 frames. 

It was discovered this was due to the lack of support for vertex normals interpolation. I added this to our local copy of the package, but it'd be nice if this was included as part of the official package.

**Comment by i-saint** [comment]
what version are you using? latest version (20180205) support normal interpolation and enabled by default.

**Comment by dmm-pete** [comment]
Ah, yes, I was using the version from Jan 23, and I see normals interpolation was added just a few days afterwards  :P Sorry about the confusion!
