### ISSUE TITLE
Vertex Sharing

### ISSUE THREAD

**Issue by haroag** [unity3d-jp/AlembicImporter#58]
Our team has updated to latest version and noticed that some of our alembics now have irregularities, 

[Irregularity](https://drive.google.com/file/d/1GzA6f0CortPb_teCDGHu9j5eD0WVQly9/view?usp=sharing)

This might be from the vertex sharing. But it seems like it might be within the DLL's. The version that we are using is Alembic Importer 1.0f1.

**Comment by i-saint** [comment]
can you send me your .abc file that can reproduce the issue?

**Comment by i-saint** [comment]
if latest package doesn't solve your problem, reopen this issue and send me your .abc file.

**Comment by haroag** [comment]
Hi @i-saint,

I tried the latest release and I still get the issue, Link to [.abc](https://www.4dviews.com/file/download/alembic/ALEMBIC_Shaolin_TaiChi_2048.zip)

Thanks.

**Comment by i-saint** [comment]
hmm, I can play it without problem. can you re-install plugin (exit Unity, delete Assets/UTJ/Alembic directory, and re-import [this package](https://github.com/unity3d-jp/AlembicImporter/releases/download/20180205/AlembicForUnity.unitypackage)) and retry?

![unity-2017](https://user-images.githubusercontent.com/1488611/36050538-3718773a-0e2a-11e8-9457-797d9146b7ff.gif)

**Comment by haroag** [comment]
what settings did you use on the import?

**Comment by i-saint** [comment]
all default.

I think I realized what you meant. certainly there are some frames that seems glitch. I will investigate.
![shaolin](https://user-images.githubusercontent.com/1488611/36051737-76c38844-0e2e-11e8-985a-aa238fed05ea.png)

**Comment by haroag** [comment]
Yes Exactly, TY. Would this be dependant on the graphics card?

**Comment by haroag** [comment]
It does the glitch in this version but then recalculates when I move around the scene to look at the glitch.

**Comment by haroag** [comment]
![shaolinalembic5](https://user-images.githubusercontent.com/16925127/36052180-703ba07a-0da1-11e8-99df-0deef53cb59f.PNG)
![shaolinalembic6](https://user-images.githubusercontent.com/16925127/36052181-70515a1e-0da1-11e8-9a96-e2ec7e2a5a08.PNG)

**Comment by i-saint** [comment]
I just figured it out. it was a stupid bug. (not graphics card-dependent)
I will send you new package. wait a moment.

**Comment by haroag** [comment]
Great Thanks

**Comment by i-saint** [comment]
this package should work. (I assume you are using Windows. Mac plugin is not updated)
[AlembicForUnity.zip](https://github.com/unity3d-jp/AlembicImporter/files/1712583/AlembicForUnity.zip)

**Comment by haroag** [comment]
Yeah, that fixed it. TY

**Comment by i-saint** [comment]
perfect! thanks for the feedback.

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180212
