### ISSUE TITLE
Subframes bug

### ISSUE THREAD

**Issue by johanwalfridson** [unity3d-jp/AlembicImporter#6]
Hi

When playing back abc files it doesn't seem to query subframes - only exact exported frames.

Try the attached abc (or "AlembicImporterExample") and set playback scale to 0.1

Thank you

[ball.zip](https://github.com/unity3d-jp/AlembicImporter/files/645784/ball.zip)

**Comment by dariopixmo** [comment]
As far as I know, Alembic does not support subframes "out of the box". It would be quite tricky to implement that, since the mesh topology can change over frames..

**Comment by i-saint** [comment]
it is expected behavior since Alembic does not support interpolation (as @dariopixmo mentioned).
we are working on USD importer / exporter. USD support interpolation and it also can load Alembic files.  it will soon be released (I think you can try it in this month).

**Comment by dariopixmo** [comment]
Wow, that sounds great, really looking forward to the new importer / exporter! Is there any chance that the new importer fixes the tangent problem from the other issue?
