### ISSUE TITLE
iOS Alembic Error

### ISSUE THREAD

**Issue by psparikh** [unity3d-jp/AlembicImporter#61]
Using version 20180205, I am trying to use the Unity Alembic Importer to ship for iOS. However, I receive the error: 

"Plugin 'abci.dll' is used from several locations:
 Assets/UTJ/Alembic/Plugins/x86/abci.dll would be copied to <PluginPath>/abci.dll
 Assets/UTJ/Alembic/Plugins/x86_64/abci.dll would be copied to <PluginPath>/abci.dll
Please fix plugin settings and try again."

Since the iPhone/iPad is 64-bit, I tried to remove the x86 .dll folder or exclude it via Plugin settings; however, xCode then gives me the error:

"DllNotFoundException: Unable to load DLL 'abci': The specified module could not be found.
  at UTJ.Alembic.aiContext.aiContextCreate (Int32 uid) [0x00000] in <filename unknown>:0 
  at UTJ.Alembic.AlembicStream.AbcLoad () [0x00000] in <filename unknown>:0 
  at UTJ.Alembic.AlembicStreamPlayer.LoadStream () [0x00000] in <filename unknown>:0"

Do you have any ideas on how to get past this? Thanks!!

**Comment by i-saint** [comment]
as document states, this plugin supports only Windows, Mac and Linux. other platforms are not planned for now. (see also https://github.com/unity3d-jp/AlembicImporter/issues/28)
