### ISSUE TITLE
Crash error with AlembicForUnity 20180205

### ISSUE THREAD

**Issue by shiyamon** [unity3d-jp/AlembicImporter#66]
If you are willing to report a bug, we strongly recommend you to:
- attach .abc file that can reproduce the issue
- write what version of package are you using (e.g. 20180205)
- attach Editor.log ( https://docs.unity3d.com/Manual/LogFiles.html )

Editor crashes just after I import abc file.

![alembicerror](https://user-images.githubusercontent.com/1924504/36063573-0120aa1a-0ec2-11e8-8ed3-0eb84f7a5c08.JPG)

I created the new empty Unity project and imported AlembicForUnity.unitypackage (20180205 one), then tried Assts->Import New Asset.
I tried some abc file that worked with old importer but made no success with all of them.

I use
Unity 2017.2.0f3
Alembic Importer 20180205

[Editor.zip](https://github.com/unity3d-jp/AlembicImporter/files/1713508/Editor.zip)

**Comment by i-saint** [comment]
can you send me your .abc file?

**Comment by shiyamon** [comment]
[obi_01.zip](https://github.com/unity3d-jp/AlembicImporter/files/1713516/obi_01.zip)

here you go.

**Comment by shiyamon** [comment]
thanks for the information. I will wait for the update!

**Comment by i-saint** [comment]
I *think* have fixed the issue. this package should work. [AlembicForUnity.zip](https://github.com/unity3d-jp/AlembicImporter/files/1713579/AlembicForUnity.zip)

![ribbon](https://user-images.githubusercontent.com/1488611/36064360-364aef6a-0ecd-11e8-9eeb-fc3f7b45d47a.gif)

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180212

**Comment by i-saint** [comment]
glad to hear your problem solved!
