### ISSUE TITLE
Can't change stream player playback settings

### ISSUE THREAD

**Issue by cmomoney** [unity3d-jp/AlembicImporter#7]
Unity 5.5.1f1 Personal

I can't seem to change the playback setting in the stream player. Are they read only?

**Comment by 0xb1dd1e** [comment]
I have this problem too in 5.6.0b6

As a quick workaround, if you switch the Inspector to 'Debug' mode you can make changes.

**Comment by cmomoney** [comment]
Works now. Thanks!
