### ISSUE TITLE
[Feature Request] Seek to Frame/Play based on frame 

### ISSUE THREAD

**Issue by haroag** [unity3d-jp/AlembicImporter#71]
It would be helpful if we could have the alembic seek to frame. It would also help if we can play based on the frame and not time. This would help with texture synchronizing.

**Comment by i-saint** [comment]
there is a reason that this plugin doesn't support frame based seeking.
Alembic can have multiple timelines. each timeline can have different time intervals. and also Alembic supports non-uniform time intervals.
for example:
- timeline 1: start time: 0s, interval: uniform 1s, 10 samples (so time range is 0s - 10s)
- timeline 2: start time: 5s, interval: uniform 0.1s , 100 samples (so time range is 5s - 15s)
- timeline 3: start time: 10s, interval: nonuniform [1s, 2s, 4s, 3s] 4 samples (so time range is 10s - 20s)

one alembic archive can have all of these timelines. as a result, "frame 1" can have different meaning (time) depend on object('s timeline).

I think AnimationEvent is more appropriate way for a case such as yours.
current version of this plugin generates animation clip that simply animates time from 0 to its duration. I can extend it to generate clips that are correspond to alembic's timeline, and each clip have AnimationEvents that correspond frames (in above case, timeline 3 will be converted as AnimationClip that have AnimationEvents at 10s, 11s, 13s, 17s, 20s with its frame number as intParameter).
do you think this is good?

**Comment by haroag** [comment]
Yeah, that sounds good. My issue is trying to synchronize movie playback and alembic playback. This solution works for driving the movie but I was looking at it the other way of having the movie drive the alembic.

**Comment by i-saint** [comment]
I'm nearly ready to release next version. I want you to test this package if you can.
[AlembicForUnity.zip](https://github.com/unity3d-jp/AlembicImporter/files/1738401/AlembicForUnity.zip)

on this package, AnimationClip that corresponds alembic frames will be generated, and it will call AbcOnFrameChange(int frame) method by AnimationEvent.
so you can animate texture by simple script like this: https://github.com/unity3d-jp/AlembicImporter/blob/dev/AlembicImporter/Assets/Tests/Scripts/AlembicTextureAnimator.cs

**Comment by haroag** [comment]
Hi @i-saint ,

I tried the new feature but couldn't get it to work, On import it generated 3 animation clips that didn't have animation curves and the last animation clip was super long. 
![animclip](https://user-images.githubusercontent.com/16925127/36447820-5ea4f310-163a-11e8-86b8-555f936f5a42.PNG)

I never was able to get the event to fire also.

**Comment by i-saint** [comment]
you need to setup Animator manually to get events to fire. in your case, drag and drop shaolin_taichi_Frames2 to the GameObject that your script (that has AbcOnFrameChange) is attached to.

also I figured it out why time range is super long and fix it. and Frame1 clip is empty because this alembic file has empty timeline.

**Comment by haroag** [comment]
ok great, i got it too work. I also noticed that total frame is 280 but the Time Range come in as 7.686-. At 3-fps framerate the time range should be 9.33?

**Comment by i-saint** [comment]
updated package is here. you need to reimport alembic asset to fix time range.
[AlembicForUnity.zip](https://github.com/unity3d-jp/AlembicImporter/files/1742299/AlembicForUnity.zip)

**Comment by haroag** [comment]
Ran into an out of memory exception when dragging out the alembic track in the timeline window.
But it worked. 

Thanks @i-saint

**Comment by i-saint** [comment]
glad to hear your problem solved!

> out of memory exception when dragging out the alembic track in the timeline window

I know it and I believe it's a Timeline's issue. probably I will add workaround for it if I got idea..

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180222
