### ISSUE TITLE
Colliding plugins on Unity build

### ISSUE THREAD

**Issue by Rlapham** [unity3d-jp/AlembicImporter#72]
Hi, 
I've been struggling with the build for some time. I get a conflicting plugin error (abci.dil): 

![m5ikza9qzy4e](https://user-images.githubusercontent.com/22139773/36406198-1fba02d4-15c3-11e8-8d70-86b67aae9f32.png)

Thank again for any help in this,

Richard

**Comment by i-saint** [comment]
error message is explaining everything. just delete duplicates.
if you need more help. send me your project data.

**Comment by Rlapham** [comment]
Thanks for getting back to me so quickly and sorry if this is a simple error. 

Any combination of deleting the plugins results in a "DllNotFoundException: abci" error in the log. I must have missed a step in setting my project up. If you have time I'll attach the player log, no worries if you're busy. 

Thanks again and best,
Richard 

[Player.log](https://github.com/unity3d-jp/AlembicImporter/files/1740624/Player.log)

**Comment by i-saint** [comment]
I said "if you need more help. send me your project data."

**Comment by Rlapham** [comment]
Sorry for the confusion. 

[Explosion2.abc.zip](https://github.com/unity3d-jp/AlembicImporter/files/1741512/Explosion2.abc.zip)

I'm using Unity 2017.3 with version 20180205. 

[Editor.log](https://github.com/unity3d-jp/AlembicImporter/files/1741517/Editor.log)

Thanks again for any help,
Richard

**Comment by i-saint** [comment]
thanks. however, alembic file is not matter in this case. what I need is your project data. minimal project that can reproduce the issue is ideal.

**Comment by Rlapham** [comment]
I see, I'll attach a barebones project with the error. 

Thanks again for your patience,
Richard 

[Day44.zip](https://github.com/unity3d-jp/AlembicImporter/files/1741697/Day44.zip)

**Comment by i-saint** [comment]
I can build it without error on my Mac (Unity 2017.3.1f1).
what is your target platform?

**Comment by Rlapham** [comment]
I tried on a different version of Unity and the same project worked. I'm figuring out why - my best guess is an incorrect architecture. 

Sorry to waste your time and thanks for all your help.
