### ISSUE TITLE
[Feature Request] Saving Transform Animation of Meshes

### ISSUE THREAD

**Issue by psparikh** [unity3d-jp/AlembicImporter#76]
Hi! I've been curious if this is possible to implement. I recognized that as you scroll through the Alembic Stream Player Time, the Scene window shows that the Transform moves (according to the average of the vertices?).

Would it be possible to actually save the local "average" of the vertices as its own animation? For example, if my alembic animation is a constant mesh being animated (through position and rotation only), instead of caching and animating all the vertices like a normal Alembic, it would intelligently identify the change in position and rotation, and create that animation (which is less intensive).

**Comment by i-saint** [comment]
I do not understand what you mean. explain in detail.
are you talking about importer or exporter? did you solved it by yourself?

**Comment by i-saint** [comment]
ok, I won't help you anymore. don't post new issues.

**Comment by psparikh** [comment]
Hi - sorry I was on vacation this weekend and just received this notification. I realized that accessing and manipulating the mesh vertices from the Alembic import would not be a feature of the importer/exporter itself. I'm attempting to solve it this week. Essentially, I want to get the local transform (and position/rotation animation) of the submeshes from an Alembic animation import with a constant mesh. I'm assuming that Alembic reads vertices in the same order on every frame.

Once again, so sorry for the lack of communication. Your tools have helped me so much. I would appreciate continuing my testing on the Alembic.
