### ISSUE TITLE
Crash when importing Blender's output Alembic file

### ISSUE THREAD

**Issue by medamap** [unity3d-jp/AlembicImporter#81]
I will report it when I import Alembic output by Blender in a specific way because it will crash.

Reproduction method

1. Import animated abc into Blender
2. Make a modification such as Decimate with a modifier
3. Export in Alembic format (check vertex color as option at that time)
4. Crash when importing 3 abc into Unity

Thank you.

- Package version 20180212
- [Editor.log](https://github.com/unity3d-jp/AlembicImporter/files/1817000/Editor.log)
- [abc before convert  Anime20180306-1900.zip](https://github.com/unity3d-jp/AlembicImporter/files/1817014/Anime20180306-1900.zip)
- [abc after conbert untitled.zip](https://github.com/unity3d-jp/AlembicImporter/files/1817001/untitled.zip)

**Comment by i-saint** [comment]
thanks for the report. I confirmed the issue on latest release.

your .abc file (after convert) has irregular data (vertex color with empty indices). Decimate modifier seems decimates the data should not be decimated... but workaround is not difficult. I will release new package in a few days.

**Comment by i-saint** [comment]
you can try this package if you are in a hurry:
[AlembicForUnity.zip](https://github.com/unity3d-jp/AlembicImporter/files/1818315/AlembicForUnity.zip)

**Comment by i-saint** [comment]
this package should work - at least it can import untitled.abc without crash, but vertex color is unexpected result (because this .abc file it is corrupted as explained above).
[AlembicForUnity.zip](https://github.com/unity3d-jp/AlembicImporter/files/1820696/AlembicForUnity.zip)

**Comment by medamap** [comment]
Thank you for your response.
I understood the problem that explained.
Animation exceeding 1.5 million vertices was very heavy on Unity, so I used Decimate, but I think I will take a different solution.
I will report to Blender which abc breaks.
Thank you.

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180320
done. also wide character path issue (#82)
